# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gherkingen < Formula
  desc "BDD tests boilerplate generator for Golang"
  homepage "https://github.com/hedhyw/gherkingen"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/gherkingen/releases/download/v2.3.0/gherkingen_darwin_amd64.tar.gz"
      sha256 "c71f73088ed6028e51f89a79c823b6d6072d4d8574360254c6217df780330f8e"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hedhyw/gherkingen/releases/download/v2.3.0/gherkingen_darwin_arm64.tar.gz"
      sha256 "b4b38e038b2cab64d586d643aa6721ca0c30db86065723109dc7b6083f06fbe6"

      def install
        bin.install "gherkingen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/gherkingen/releases/download/v2.3.0/gherkingen_linux_amd64.tar.gz"
      sha256 "3cee639a8afc73872793eb8bf3f373e044380632749775b0b99630c7f5b2dfa4"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/gherkingen/releases/download/v2.3.0/gherkingen_linux_arm.tar.gz"
      sha256 "b2c090350824ea89f97aad4bfa8a72b7f01243e61b0bf58d2aafb9ace2bc23c5"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/gherkingen/releases/download/v2.3.0/gherkingen_linux_arm64.tar.gz"
      sha256 "b7c2d8ea7de3960ff5b9a804b8e46362f96d08845cb15a87997e6bb78a40d11d"

      def install
        bin.install "gherkingen"
      end
    end
  end

  test do
    system "#{bin}/gherkingen", "-help"
  end
end
