# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gherkingen < Formula
  desc "BDD tests boilerplate generator for Golang"
  homepage "https://github.com/hedhyw/gherkingen"
  version "3.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hedhyw/gherkingen/releases/download/v3.0.2/gherkingen_darwin_arm64.tar.gz"
      sha256 "98bf1b5952afa35c1a9b47fbe6c44759777cc2645f556d744a28c279c29b6a56"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/gherkingen/releases/download/v3.0.2/gherkingen_darwin_amd64.tar.gz"
      sha256 "8cc0db1e3f80cef002c7865aa36d0d131ef4841bf06d0a502a35113987d00058"

      def install
        bin.install "gherkingen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/gherkingen/releases/download/v3.0.2/gherkingen_linux_arm.tar.gz"
      sha256 "68e52ca8280e2d1f6b79fb6a39ca5f4d3b789a6232c6799058df8723ee5f6b5a"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/gherkingen/releases/download/v3.0.2/gherkingen_linux_amd64.tar.gz"
      sha256 "63e7154a083e2f8f3ec5adfd596915e8f1b407fcce36908b9dda2362bc928fed"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/gherkingen/releases/download/v3.0.2/gherkingen_linux_arm64.tar.gz"
      sha256 "3d93d6ef97de7eb01debf974ed8bee1392ec7e0eb3be39d2ba3be3afa8572b69"

      def install
        bin.install "gherkingen"
      end
    end
  end

  test do
    system "#{bin}/gherkingen", "-help"
  end
end
