# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gherkingen < Formula
  desc "BDD tests boilerplate generator for Golang"
  homepage "https://github.com/hedhyw/gherkingen"
  version "3.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hedhyw/gherkingen/releases/download/v3.0.1/gherkingen_darwin_arm64.tar.gz"
      sha256 "27ad3f97fbe3c86edbe2f37510c831257d52dae92338ee658d447fc3db89cafa"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/gherkingen/releases/download/v3.0.1/gherkingen_darwin_amd64.tar.gz"
      sha256 "a94bcde65dd7a3489b834dbe34a786e86a4bb7bc3cbe4211c8621cb96385e836"

      def install
        bin.install "gherkingen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/gherkingen/releases/download/v3.0.1/gherkingen_linux_amd64.tar.gz"
      sha256 "ef570845145918460071db1d7c6a31609c5e5c951c7b2c4962907a2ac29af5c7"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/gherkingen/releases/download/v3.0.1/gherkingen_linux_arm.tar.gz"
      sha256 "c0bdebb5b267dac96f97fd33dca5ad21b8c246ec1db373dad59554c38008e7de"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/gherkingen/releases/download/v3.0.1/gherkingen_linux_arm64.tar.gz"
      sha256 "c9f1098e70a3cd299fcd530025dc11d7808f02eb98a5c8a70cb7918f492520d3"

      def install
        bin.install "gherkingen"
      end
    end
  end

  test do
    system "#{bin}/gherkingen", "-help"
  end
end
